"""Data access layer for Supabase tables.

This module provides typed helper functions for database operations,
abstracting away the Supabase client query builder.
"""

# Users
# Analytics
from app.db.tables.analytics import (
    create_analytics_snapshot,
    create_audit_event,
    create_auto_pipeline,
    create_visibility_snapshot,
    delete_analytics_snapshot,
    delete_audit_event,
    delete_auto_pipeline,
    delete_visibility_snapshot,
    get_analytics_snapshot_by_id,
    get_analytics_snapshot_by_project_and_date,
    get_audit_event_by_id,
    get_auto_pipeline_by_id,
    get_visibility_snapshot_by_id,
    list_analytics_snapshots_for_project,
    list_audit_events_for_workspace,
    list_auto_pipelines_for_project,
    list_visibility_snapshots_for_project,
    update_analytics_snapshot,
    update_auto_pipeline,
)

# Campaigns
from app.db.tables.campaigns import (
    create_campaign,
    create_published_post,
    delete_campaign,
    delete_published_post,
    get_campaign_by_id,
    get_published_post_by_id,
    list_campaigns_for_project,
    list_published_posts_for_campaign,
    list_published_posts_for_project,
    update_campaign,
    update_published_post,
)

# Competitors
from app.db.tables.competitors import (
    count_competitor_mentions,
    create_competitor_mention,
    get_competitor_mention_by_opportunity,
    get_competitor_stats,
    list_competitor_mentions,
)

# Content
from app.db.tables.content import (
    create_post_draft,
    create_reply_draft,
    delete_post_draft,
    delete_reply_draft,
    get_draft_by_project_and_opportunity,
    get_post_draft_by_id,
    get_reply_draft_by_id,
    list_post_drafts_for_project,
    list_reply_drafts_for_opportunity,
    list_reply_drafts_for_project,
    update_post_draft,
    update_reply_draft,
)

# Discovery
from app.db.tables.discovery import (
    bulk_create_opportunities,
    count_opportunities_for_project,
    create_discovery_keyword,
    create_monitored_subreddit,
    create_opportunity,
    create_persona,
    create_scan_run,
    create_subreddit_analysis,
    delete_discovery_keyword,
    delete_monitored_subreddit,
    delete_opportunity,
    delete_persona,
    delete_scan_run,
    get_discovery_keyword_by_id,
    get_keyword_by_project_and_keyword,
    get_monitored_subreddit_by_id,
    get_opportunity_by_id,
    get_opportunity_by_project_and_reddit_post,
    get_persona_by_id,
    get_scan_run_by_id,
    get_subreddit_by_project_and_name,
    list_discovery_keywords_for_project,
    list_keywords_for_project,
    list_monitored_subreddits_for_project,
    list_opportunities_for_project,
    list_personas_for_project,
    list_scan_runs_for_project,
    list_subreddits_for_project,
    update_discovery_keyword,
    update_monitored_subreddit,
    update_opportunity,
    update_persona,
    update_scan_run,
)

# Integrations
from app.db.tables.integrations import (
    create_integration_secret,
    create_reddit_account,
    delete_integration_secret,
    delete_reddit_account,
    get_integration_secret_by_id,
    get_integration_secret_by_provider_and_label,
    get_reddit_account_by_id,
    get_reddit_account_by_workspace_and_username,
    list_integration_secrets_for_workspace,
    list_reddit_accounts_for_workspace,
    update_integration_secret,
    update_reddit_account,
)

# Projects
from app.db.tables.projects import (
    create_brand_profile,
    create_project,
    create_prompt_template,
    delete_brand_profile,
    delete_project,
    delete_prompt_template,
    ensure_default_prompts_exist,
    get_brand_profile_by_id,
    get_brand_profile_by_project,
    get_default_prompts,
    get_project_by_id,
    get_project_by_slug,
    get_projects_by_ids,
    get_prompt_template_by_id,
    list_projects_for_workspace,
    list_prompt_templates_for_project,
    update_brand_profile,
    update_project,
    update_prompt_template,
)

# System (notifications, activity logs, usage metrics)
from app.db.tables.system import (
    create_activity_log,
    create_notification,
    create_usage_metric,
    delete_activity_log,
    delete_notification,
    delete_usage_metric,
    get_activity_log_by_id,
    get_notification_by_id,
    get_usage_metric_by_id,
    get_usage_metric_by_workspace_and_key,
    list_activity_logs_for_workspace,
    list_notifications_for_workspace,
    list_usage_metrics_for_workspace,
    mark_notification_read,
    update_notification,
    update_usage_metric,
)
from app.db.tables.users import (
    create_user,
    delete_user,
    get_user_by_email,
    get_user_by_id,
    get_user_by_supabase_id,
    list_users_by_workspace,
    update_user,
)

# Visibility
from app.db.tables.visibility import (
    count_ai_responses_with_brand_mention_for_project,
    count_ai_responses_with_model_and_mention,
    count_citations_for_project,
    count_prompt_runs_for_project,
    count_prompt_runs_with_model,
    create_ai_response,
    create_brand_mention,
    create_citation,
    create_prompt_run,
    create_prompt_set,
    create_source_domain,
    create_source_gap,
    delete_ai_response,
    delete_brand_mention,
    delete_citation,
    delete_prompt_run,
    delete_prompt_set,
    delete_source_domain,
    delete_source_gap,
    get_ai_response_by_id,
    get_brand_mention_by_id,
    get_citation_by_id,
    get_prompt_run_by_id,
    get_prompt_set_by_id,
    get_source_domain_by_id,
    get_source_gap_by_id,
    list_ai_responses_for_prompt_run,
    list_ai_responses_for_runs,
    list_brand_mentions_for_ai_response,
    list_citations_for_ai_response,
    list_citations_for_project,
    list_citations_for_prompt_sets,
    list_prompt_runs_for_prompt_set,
    list_prompt_sets_for_project,
    list_source_domains_for_project,
    list_source_gaps_for_project,
    update_ai_response,
    update_prompt_run,
    update_prompt_set,
    update_source_domain,
)

# Webhooks
from app.db.tables.webhooks import (
    create_webhook_endpoint,
    delete_webhook_endpoint,
    get_webhook_endpoint_by_id,
    list_webhook_endpoints_for_workspace,
    update_webhook_endpoint,
)

# Workspaces
from app.db.tables.workspaces import (
    create_invitation,
    create_membership,
    create_redemption,
    create_subscription,
    create_workspace,
    delete_invitation,
    delete_membership,
    delete_subscription,
    delete_workspace,
    get_entitlement,
    get_invitation_by_id,
    get_invitation_by_token,
    get_invitation_by_workspace_and_email,
    get_membership,
    get_membership_by_id,
    get_membership_by_user_and_workspace,
    get_plan_entitlements,
    get_redemption_by_code,
    get_subscription_by_id,
    get_subscription_by_workspace,
    get_workspace_by_id,
    get_workspace_by_slug,
    list_invitations_for_workspace,
    list_memberships_for_user,
    list_memberships_for_workspace,
    list_workspaces_for_user,
    update_invitation,
    update_membership,
    update_redemption,
    update_subscription,
    update_workspace,
)

__all__ = [
    # Users
    "get_user_by_id",
    "get_user_by_supabase_id",
    "get_user_by_email",
    "create_user",
    "update_user",
    "delete_user",
    "list_users_by_workspace",
    # Workspaces
    "get_workspace_by_id",
    "get_workspace_by_slug",
    "create_workspace",
    "update_workspace",
    "delete_workspace",
    "list_workspaces_for_user",
    "get_membership",
    "get_membership_by_id",
    "create_membership",
    "update_membership",
    "delete_membership",
    "list_memberships_for_workspace",
    "list_memberships_for_user",
    "get_invitation_by_token",
    "get_invitation_by_id",
    "create_invitation",
    "update_invitation",
    "delete_invitation",
    "list_invitations_for_workspace",
    "get_invitation_by_workspace_and_email",
    "get_membership_by_user_and_workspace",
    "get_subscription_by_workspace",
    "get_subscription_by_id",
    "create_subscription",
    "update_subscription",
    "delete_subscription",
    "get_plan_entitlements",
    "get_entitlement",
    "get_redemption_by_code",
    "create_redemption",
    "update_redemption",
    # Projects
    "get_project_by_id",
    "get_project_by_slug",
    "create_project",
    "update_project",
    "delete_project",
    "list_projects_for_workspace",
    "get_projects_by_ids",
    "get_brand_profile_by_project",
    "get_brand_profile_by_id",
    "create_brand_profile",
    "update_brand_profile",
    "delete_brand_profile",
    "get_prompt_template_by_id",
    "get_default_prompts",
    "create_prompt_template",
    "update_prompt_template",
    "delete_prompt_template",
    "list_prompt_templates_for_project",
    "ensure_default_prompts_exist",
    # Competitors
    "create_competitor_mention",
    "list_competitor_mentions",
    "get_competitor_mention_by_opportunity",
    "get_competitor_stats",
    "count_competitor_mentions",
    # Discovery
    "get_persona_by_id",
    "create_persona",
    "update_persona",
    "delete_persona",
    "get_discovery_keyword_by_id",
    "list_keywords_for_project",
    "create_discovery_keyword",
    "update_discovery_keyword",
    "delete_discovery_keyword",
    "get_keyword_by_project_and_keyword",
    "get_monitored_subreddit_by_id",
    "list_subreddits_for_project",
    "create_monitored_subreddit",
    "update_monitored_subreddit",
    "delete_monitored_subreddit",
    "get_subreddit_by_project_and_name",
    "create_subreddit_analysis",
    "get_scan_run_by_id",
    "list_scan_runs_for_project",
    "create_scan_run",
    "update_scan_run",
    "delete_scan_run",
    "get_opportunity_by_id",
    "get_opportunity_by_project_and_reddit_post",
    "list_opportunities_for_project",
    "create_opportunity",
    "update_opportunity",
    "delete_opportunity",
    "bulk_create_opportunities",
    "count_opportunities_for_project",
    "list_personas_for_project",
    "list_discovery_keywords_for_project",
    "list_monitored_subreddits_for_project",
    # Content
    "get_reply_draft_by_id",
    "list_reply_drafts_for_opportunity",
    "list_reply_drafts_for_project",
    "create_reply_draft",
    "update_reply_draft",
    "delete_reply_draft",
    "get_draft_by_project_and_opportunity",
    "get_post_draft_by_id",
    "list_post_drafts_for_project",
    "create_post_draft",
    "update_post_draft",
    "delete_post_draft",
    # Visibility
    "get_prompt_set_by_id",
    "list_prompt_sets_for_project",
    "create_prompt_set",
    "update_prompt_set",
    "delete_prompt_set",
    "get_prompt_run_by_id",
    "list_prompt_runs_for_prompt_set",
    "create_prompt_run",
    "update_prompt_run",
    "delete_prompt_run",
    "get_ai_response_by_id",
    "list_ai_responses_for_prompt_run",
    "create_ai_response",
    "update_ai_response",
    "delete_ai_response",
    "get_brand_mention_by_id",
    "list_brand_mentions_for_ai_response",
    "create_brand_mention",
    "delete_brand_mention",
    "get_citation_by_id",
    "list_citations_for_ai_response",
    "create_citation",
    "delete_citation",
    "get_source_domain_by_id",
    "list_source_domains_for_project",
    "create_source_domain",
    "update_source_domain",
    "delete_source_domain",
    "get_source_gap_by_id",
    "list_source_gaps_for_project",
    "create_source_gap",
    "delete_source_gap",
    "list_ai_responses_for_runs",
    "count_prompt_runs_for_project",
    "count_ai_responses_with_brand_mention_for_project",
    "count_citations_for_project",
    "count_prompt_runs_with_model",
    "count_ai_responses_with_model_and_mention",
    "list_citations_for_prompt_sets",
    "list_citations_for_project",
    "list_source_domains_for_project",
    # Analytics
    "get_analytics_snapshot_by_id",
    "get_analytics_snapshot_by_project_and_date",
    "list_analytics_snapshots_for_project",
    "create_analytics_snapshot",
    "update_analytics_snapshot",
    "delete_analytics_snapshot",
    "get_audit_event_by_id",
    "list_audit_events_for_workspace",
    "create_audit_event",
    "delete_audit_event",
    "get_auto_pipeline_by_id",
    "list_auto_pipelines_for_project",
    "create_auto_pipeline",
    "update_auto_pipeline",
    "delete_auto_pipeline",
    "get_visibility_snapshot_by_id",
    "list_visibility_snapshots_for_project",
    "create_visibility_snapshot",
    "delete_visibility_snapshot",
    # Other
    "get_campaign_by_id",
    "list_campaigns_for_project",
    "create_campaign",
    "update_campaign",
    "delete_campaign",
    "get_published_post_by_id",
    "list_published_posts_for_project",
    "list_published_posts_for_campaign",
    "create_published_post",
    "update_published_post",
    "delete_published_post",
    "get_webhook_endpoint_by_id",
    "list_webhook_endpoints_for_workspace",
    "create_webhook_endpoint",
    "update_webhook_endpoint",
    "delete_webhook_endpoint",
    "get_integration_secret_by_id",
    "list_integration_secrets_for_workspace",
    "get_integration_secret_by_provider_and_label",
    "create_integration_secret",
    "update_integration_secret",
    "delete_integration_secret",
    "get_reddit_account_by_id",
    "list_reddit_accounts_for_workspace",
    "get_reddit_account_by_workspace_and_username",
    "create_reddit_account",
    "update_reddit_account",
    "delete_reddit_account",
    "get_notification_by_id",
    "list_notifications_for_workspace",
    "create_notification",
    "update_notification",
    "delete_notification",
    "mark_notification_read",
    "get_activity_log_by_id",
    "list_activity_logs_for_workspace",
    "create_activity_log",
    "delete_activity_log",
    "get_usage_metric_by_id",
    "get_usage_metric_by_workspace_and_key",
    "list_usage_metrics_for_workspace",
    "create_usage_metric",
    "update_usage_metric",
    "delete_usage_metric",
]
